CREATE TABLE recruiters(
id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
user_id UUID REFERENCES users(id) ON DELETE CASCADE,
company_name VARCHAR(150) NOT NULL,
industry VARCHAR(100),
location VARCHAR(100),
hr_name VARCHAR(100),
logo_url VARCHAR(255),
Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);