CREATE TABLE portfolios(
id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
student_id UUID REFERENCES students(id) ON DELETE CASCADE,
slug VARCHAR(100) UNIQUE NOT NULL,
template_id VARCHAR(50),
is_live BOOLEAN DEFAULT FALSE,
views INTEGER DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);